### ISSUE TITLE
Broken Links Are Being Made

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/subete#17]
See this error:

```
E:\Projects\sample-programs-docs-generator\venv\Scripts\python.exe E:/Projects/sample-programs-docs-generator/generate_docs/generator.py E:\Projects\sample-programs\archive
Traceback (most recent call last):
  File "E:\Projects\sample-programs-docs-generator\generate_docs\generator.py", line 75, in <module>
    main_readmes()
  File "E:\Projects\sample-programs-docs-generator\generate_docs\generator.py", line 65, in main_readmes
    _create_generator().generate_readmes()
  File "E:\Projects\sample-programs-docs-generator\generate_docs\generator.py", line 34, in generate_readmes
    readme_catalog = ReadMeCatalog(self.repo)
  File "E:\Projects\sample-programs-docs-generator\generate_docs\readme.py", line 66, in __init__
    self._build_readmes()
  File "E:\Projects\sample-programs-docs-generator\generate_docs\readme.py", line 117, in _build_readmes
    self._build_readme(language)
  File "E:\Projects\sample-programs-docs-generator\generate_docs\readme.py", line 83, in _build_readme
    page.add_element(_generate_program_list(language))
  File "E:\Projects\sample-programs-docs-generator\generate_docs\readme.py", line 36, in _generate_program_list
    if not program_line.verify_urls()[program.documentation_url()]:
  File "E:\Projects\sample-programs-docs-generator\venv\lib\site-packages\snakemd\generator.py", line 646, in verify_urls
    result[item._url] = item.is_url() and item.verify_url()
  File "E:\Projects\sample-programs-docs-generator\venv\lib\site-packages\snakemd\generator.py", line 137, in verify_url
    request.urlopen(req)
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1385, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1100, in putrequest
    self._validate_path(url)
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1200, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/projects/hello-world/Google Apps Script' (found at least ' ')

Process finished with exit code 1
```

**Comment by jrg94** [comment]
Looks like issue URLs are broken too. See table:

```
The following table contains all the existing languages in the repository that start with the letter G:

| Language                                                                                       | Article(s)                                                                        | Issue(s)                                                                                                  | Test(s)                                                                                           | # of Snippets |
| ---------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------- | ------------- |
| [Gerbil](/TheRenegadeCoder/sample-programs/tree/main/archive/g/Gerbil)                         |                                                                                   | [Here](/TheRenegadeCoder/sample-programs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Gerbil)             |                                                                                                   | 1             |
| [Gluon](/TheRenegadeCoder/sample-programs/tree/main/archive/g/Gluon)                           |                                                                                   | [Here](/TheRenegadeCoder/sample-programs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Gluon)              |                                                                                                   | 1             |
| [Go](/TheRenegadeCoder/sample-programs/tree/main/archive/g/Go)                                 |                                                                                   | [Here](/TheRenegadeCoder/sample-programs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Go)                 | [Here](https://github.com/TheRenegadeCoder/sample-programs/blob/main/archive/g/go/testinfo.yml)   | 22            |
| [Goby](/TheRenegadeCoder/sample-programs/tree/main/archive/g/Goby)                             | [Here](https://sample-programs.therenegadecoder.com/languages/goby)               | [Here](/TheRenegadeCoder/sample-programs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Goby)               | [Here](https://github.com/TheRenegadeCoder/sample-programs/blob/main/archive/g/goby/testinfo.yml) | 1             |
| [Golo](/TheRenegadeCoder/sample-programs/tree/main/archive/g/Golo)                             |                                                                                   | [Here](/TheRenegadeCoder/sample-programs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Golo)               |                                                                                                   | 1             |
| [Google Apps Script](/TheRenegadeCoder/sample-programs/tree/main/archive/g/Google Apps Script) | [Here](https://sample-programs.therenegadecoder.com/languages/google-apps-script) | [Here](/TheRenegadeCoder/sample-programs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Google Apps Script) |                                                                                                   | 1             |
| [Gosu](/TheRenegadeCoder/sample-programs/tree/main/archive/g/Gosu)                             |                                                                                   | [Here](/TheRenegadeCoder/sample-programs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Gosu)               |                                                                                                   | 1             |
| [Grain](/TheRenegadeCoder/sample-programs/tree/main/archive/g/Grain)                           |                                                                                   | [Here](/TheRenegadeCoder/sample-programs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Grain)              |                                                                                                   | 1             |
| [Granule](/TheRenegadeCoder/sample-programs/tree/main/archive/g/Granule)                       |                                                                                   | [Here](/TheRenegadeCoder/sample-programs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Granule)            |                                                                                                   | 1             |
| [Gravity](/TheRenegadeCoder/sample-programs/tree/main/archive/g/Gravity)                       |                                                                                   | [Here](/TheRenegadeCoder/sample-programs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Gravity)            |                                                                                                   | 1             |
| [Groovy](/TheRenegadeCoder/sample-programs/tree/main/archive/g/Groovy)                         |                                                                                   | [Here](/TheRenegadeCoder/sample-programs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Groovy)             |                                                                                                   | 8             |
| **Totals**                                                                                     |                                                                                   |                                                                                                           |                                                                                                   | 39            |

< [Previous (F)](/TheRenegadeCoder/sample-programs/wiki/F) | [Next (H)](/TheRenegadeCoder/sample-programs/wiki/H) >
```
